# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_card.ipynb.

# %% auto 0
__all__ = ['Card']

# %% ../nbs/00_card.ipynb 9
class Card:
    "A playing card"
    def __init__(self,
                 suit,
                 rank):
        self.suit, self.rank = suit, rank
    def __str__(self): return f"{ranks[self.rank]}{suits[self.suit]}"
    __repr__= __str__

# %% ../nbs/00_card.ipynb 12
@patch
def __eq__(self:Card, a: Card): return (self.suit, self.rank) == (a.suit, a.rank)

# %% ../nbs/00_card.ipynb 14
@patch 
def __gt__(self: Card, a:Card): return (self.suit, self.rank) > (a.suit, a.rank)
