# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_deck.ipynb.

# %% auto 0
__all__ = ['Deck']

# %% ../nbs/00_deck.ipynb 3
class Deck:
    def __init__(self): self.cards = [Card(s,r) for s in range(4) for r in range(1,14)]
